classes:
- system.linux.system.single
- system.linux.system.repo.mcp.extra
- system.linux.system.repo.mcp.salt
- system.linux.system.repo.ubuntu
- system.openssh.server.team.all
- system.rsyslog.client.single
parameters:
  _jenkins:
    tests_enabled: false
  _param:
    # infra service addresses
    infra_config_hostname: cfg01
    infra_config_address: 172.16.10.100
    infra_config_deploy_address: 192.168.10.90

    cluster_domain: virtual-mcp11-k8s-calico.local
    cluster_name: virtual-mcp11-k8s-calico
    apt_mk_version: nightly
    primary_interface: ens3
  linux:
    network:
      host:
        cfg01:
          address: ${_param:infra_config_address}
          names:
          - ${_param:infra_config_hostname}
          - ${_param:infra_config_hostname}.${_param:cluster_domain}
      interface:
        primary_interface:
          enabled: true
          type: eth
          proto: dhcp
          #proto: static
          #name: ${_param:primary_interface}
          #address: ${_param:single_address}
          #netmask: 255.255.255.0
    system:
      name: ${_param:infra_config_hostname}
      domain: ${_param:cluster_domain}
