
classes:
- system.linux.system.single
- system.openssh.server.team.lab
- system.openssh.server.team.tcpcloud
- system.openssh.server.team.mcp_qa
- system.rsyslog.client.single
- cluster.virtual-mcp11-k8s-calico.kubernetes
- cluster.overwrite
parameters:
  _param:
    # infra service addresses
    infra_config_hostname: cfg01
    infra_config_address: 192.168.10.100
    infra_config_deploy_address: 192.168.10.100

    cluster_domain: virtual-mcp11-k8s-calico.local
    cluster_name: virtual-mcp11-k8s-calico
    #cluster_public_host: ""
  linux:
    network:
      host:
        cfg01:
          address: ${_param:infra_config_address}
          names:
          - ${_param:infra_config_hostname}
          - ${_param:infra_config_hostname}.${_param:cluster_domain}
      interface:
        ens4:
          enabled: true
          type: eth
          proto: static
          address: ${_param:single_address}
          netmask: 255.255.255.0
    system:
      name: ${_param:infra_config_hostname}
      domain: ${_param:cluster_domain}
