parameters:
  _jenkins:
    tests_enabled: false
  _param:
    cluster_domain: sl-os-contrail.local
    cluster_name: sl-os-contrail
    infra_config_deploy_address: 192.168.10.90
    infra_config_address: 172.16.10.100
    infra_config_hostname: cfg01
    linux_system_repo_mcp_salt_version: nightly
  linux:
    network:
      host:
        cfg01:
          address: ${_param:infra_config_address}
          names:
          - ${_param:infra_config_hostname}
          - ${_param:infra_config_hostname}.${_param:cluster_domain}
        cfg:
          address: ${_param:infra_config_address}
          names:
          - cfg
          - cfg.${_param:cluster_domain}
