parameters:
  _jenkins:
    tests_enabled: false
  _param:
    cluster_domain: model-manager.local
    cluster_name: model-manager
    infra_config_hostname: cfg01
    infra_config_deploy_address: 192.168.10.90
    infra_config_address: 172.16.10.100
    cluster_public_host: mm.mcp.mirantis.net
  linux:
    network:
      host:
        cfg01:
          address: ${_param:infra_config_address}
          names:
          - ${_param:infra_config_hostname}
          - ${_param:infra_config_hostname}.${_param:cluster_domain}
          - mm.mcp.mirantis.net
        cfg:
          address: ${_param:infra_config_address}
          names:
          - cfg
          - cfg.${_param:cluster_domain}
